# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

version: "2.4"

services:

  pri-fidoiot-reseller:
    image: pri-fidoiot-reseller
    container_name: pri-fidoiot-reseller
    expose:
      - "8070"
    ports:
      - "8070:8070"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - _JAVA_OPTIONS
    restart: on-failure:5
    env_file:
      - ./reseller.env
    volumes:
      - ./target:/home/reseller/target
    mem_limit: 500m
    mem_reservation: 200m
    cpu_shares: 1024
    pids_limit: 100
    network_mode: host