version: 2
updates:
  - package-ecosystem: docker
    directory: /build
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /component-samples/demo/aio
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /component-samples/demo/device
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /component-samples/demo/manufacturer
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /component-samples/demo/owner
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /component-samples/demo/reseller
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /component-samples/demo/rv
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
