# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

version: "2.4"

services:

  pri-fdo-rv:
    image: pri-fdo-rv
    container_name: pri-fdo-rv
    expose:
      - "8040"
      - "8041"
    ports:
      - "8040:8040"
      - "8041:8041"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - _JAVA_OPTIONS
    restart: on-failure:5
    env_file:
      - service.env
    volumes:
      - ./app-data:/home/fdo/app-data 
    mem_limit: 500m
    mem_reservation: 200m
    cpu_shares: 1024
    pids_limit: 500
    network_mode: host
