#!/bin/sh
#
# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0
#
# WARNING: THIS FILE CONTAINS DEMO CODE THAT IS NOT INTENDED FOR SECURE
# DEPLOYMENT. CUSTOMERS MUST REPLACE THESE CLASSES WITH AN IMPLEMENTATION THAT
# IS SECURE WITHIN THEIR ENVIRONMENT.
#

# The pattern to find the binary executable file
bin_file=rendezvous*.war

# Base-directory where all binaries are found. This should be the base of the
# folder to which binary package is extracted.
base_dir=$(realpath ../..)

# Find the absolute path of executable file.
bin_path=$(find $base_dir -name $bin_file)

# Run the executable file
if [ -z "$bin_path" ]; then
  echo "Couldn't find binary file. Please recheck binary package"
else
  exec java -jar $bin_path
fi
