# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

version: "2.4"

services:

  pri-fidoiot-rv:
    image: pri-fidoiot-rv
    container_name: pri-fidoiot-rv
    expose:
      - "8040"
    ports:
      - "8040:8040"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - _JAVA_OPTIONS
    restart: on-failure:5
    env_file:
      - rv.env
    volumes:
      - ./target:/home/rv/target
    mem_limit: 500m
    mem_reservation: 200m
    cpu_shares: 1024
    pids_limit: 100
    network_mode: host