hibernate-properties:
  hibernate.connection.username: $(db_user)
  hibernate.connection.password: $(db_password)
  hibernate.connection.url: jdbc:mariadb://host.docker.internal:3306/emdb?useSSL=$(useSSL)
  hibernate.connection.requireSSL: $(requireSSL)
  hibernate.connection.autoReconnect: true
  hibernate.dialect: org.hibernate.dialect.MariaDBDialect

system-properties:
  log4j.configurationFile: log4j2.xml
  app-data.dir: ./app-data
  application.version: 1.1.1-SNAPSHOT
  server.api.user: $(api_user)
  server.api.password: "$(api_password)"
  service.name: "Reseller"
  javax.net.debug: ssl:handshake
  #javax.net.ssl.keyStore: ./app-data/client-store.jks
  #javax.net.ssl.keyStorePassword: $(store_password)
  #javax.net.ssl.trustStorePassword: $(store_password)
  #javax.net.ssl.trustStore: ./app-data/ca-certs.jks
  #javax.net.ssl.keyStoreType: PEMS
  #javax.net.ssl.trustStoreType: PEM
  #log4j.logger.org.apache.http.impl.conn: DEBUG
  #log4j.logger.org.apache.http.impl.client: DEBUG
  #log4j.logger.org.apache.http.client: DEBUG
  # set system proxy information
  #http.proxyHost:
  #http.proxyPort:
  #https.proxyHost:
  #https.proxyPort:
  #http.nonProxyHosts:
  

http-server:
  base_path: .
  http_port: 8070
  https_port: 8072
  http_schemes:
  - http
  - https
  http_timeout: 20000
  keystore: 
    path: ./app-data/ssl-host.pem
    store-type: PEM
    password: ''
    alias: ssl
  truststore: ./app-data/ca-certs.pem
  certificate_verification: want
  certificate_verification_depth: 2


owner:
   keystore: 
     path: owner.p12
     store-type: PKCS12
     password: $(encrypt_password)

workers:
  - org.fidoalliance.fdo.protocol.StandardLogProvider
  - org.fidoalliance.fdo.protocol.StandardMessageDispatcher
  - org.fidoalliance.fdo.protocol.StandardCryptoService
  - org.fidoalliance.fdo.protocol.StandardHttpServer
  - org.fidoalliance.fdo.protocol.StandardDatabaseServer
  - org.fidoalliance.fdo.protocol.StandardOwnerKeySupplier
  - org.fidoalliance.fdo.protocol.db.StandardExtraInfoSupplier
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreInputStream
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreOutputStream
  - org.fidoalliance.fdo.protocol.db.StandardValidityDaysSupplier
