hibernate-properties:
  hibernate.connection.username: $(db_user)
  hibernate.connection.password: $(db_password)
  hibernate.connection.url: jdbc:mariadb://host.docker.internal:3306/emdb?useSSL=$(useSSL)
  hibernate.connection.requireSSL: $(requireSSL)
  hibernate.connection.autoReconnect: true
  hibernate.dialect: org.hibernate.dialect.MariaDBDialect

system-properties:
  log4j.configurationFile: log4j2.xml
  app-data.dir: ./app-data
  application.version: 1.1.7
  service.name: "Reseller"
  server.api.user: $(api_user)
  server.api.password: "null"
  javax.net.ssl.keyStorePassword: default
  javax.net.ssl.trustStorePassword: default
  javax.net.ssl.keyStore: $(secrets.path)/api-user.pem
  javax.net.ssl.trustStore: $(secrets.path)/ca-cert.pem
  javax.net.ssl.keyStoreType: PEM
  javax.net.ssl.trustStoreType: PEM
  #javax.net.debug: ssl:handshake
  #log4j.logger.org.apache.http.impl.conn: DEBUG
  #log4j.logger.org.apache.http.impl.client: DEBUG
  #log4j.logger.org.apache.http.client: DEBUG
  # set system proxy information
  #http.proxyHost:
  #http.proxyPort:
  #https.proxyHost:
  #https.proxyPort:
  #http.nonProxyHosts:


secrets:
  - db_password


http-server:
  base_path: .
  http_port: 8070
  https_port: 8072
  http_schemes:
  - http
  - https
  http_timeout: 20000
  server_cert: $(secrets.path)/server-cert.pem
  server_key: $(secrets.path)/server-key.pem
  truststore_file: $(secrets.path)/ca-cert.pem
  truststore_type: PEM
  certificate_verification: want
  protocols: TLSv1.3
  certificate_verification_depth: 2

owner:
   keystore: 
     path: reseller.p12
     store-type: PKCS12
     password: $(encrypt_password)

workers:
  - org.fidoalliance.fdo.protocol.StandardLogProvider
  - org.fidoalliance.fdo.protocol.StandardExceptionConsumer
  - org.fidoalliance.fdo.protocol.StandardMessageDispatcher
  - org.fidoalliance.fdo.protocol.StandardCryptoService
  - org.fidoalliance.fdo.protocol.StandardHttpServer
  - org.fidoalliance.fdo.protocol.StandardDatabaseServer
  - org.fidoalliance.fdo.protocol.StandardOwnerKeySupplier
  - org.fidoalliance.fdo.protocol.db.StandardExtraInfoSupplier
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreInputStream
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreOutputStream
  #- org.fidoalliance.fdo.protocol.FileKeyStoreInputStream
  #- org.fidoalliance.fdo.protocol.FileKeyStoreOutputStream
  - org.fidoalliance.fdo.protocol.db.StandardValidityDaysSupplier
