hibernate-properties:
  connection.driver_class: org.h2.Driver
  hibernate.connection.username: $(db_user)
  hibernate.connection.password: $(db_password)
  hibernate.connection.url: jdbc:h2:tcp://localhost:9092/./app-data/emdb
  hibernate.dialect: org.hibernate.dialect.H2Dialect

system-properties:
  log4j.configurationFile: log4j2.xml
  app-data.dir: ./app-data
  application.version: 1.1-SNAPSHOT
  service.name: "All-in-one demo"
  # set system proxy information
  #http.proxyHost: proxy-chain.intel.com 
  #http.proxyPort: 911
  #https.proxyHost: proxy-chain.intel.com 
  #https.proxyPort: 912
  #http.nonProxyHosts: localhost|host.example.com
  

http-server:
  base_path: app-data
  http_port: 8080
  https_port: 8443
  http_schemes:
  - http
  - https
  http_timeout: 20000
  keystore: 
    path: ssl.p12
    store-type: PKCS12
    password: $(ssl_password)
    alias: ssl
  auth:
    method: DIGEST
    role: api
    user_name: apiUser
    user_password: $(api_password)
  subject_names:
    - DNS:localhost
    - IP:127.0.0.1
  to0-scheduler:
    thread-count: 5
    interval: 120

manufacturer:
   keystore: 
     path: manufacturer.p12
     store-type: PKCS12
     password: $(encrypt_password)
   rv-instruction:
     dns: localhost
     ip: 127.0.0.1
     protocol: 1
     ownerport: 8443
     devport: 8080

owner:
   keystore: 
     path: owner.p12
     store-type: PKCS12
     password: $(encrypt_password)
   replacement:
     keystore: 
       path: replacement.p12
       store-type: PKCS12
       password: $(encrypt_password)
   to0-scheduler:
    thread-count: 5
    interval: 120


h2-database:
   tcp-server: 
     - "-ifNotExists"
   web-server:
     - "-webPort"
     - "8082"
   # - "-webAllowOthers"
   # - "-webExternalNames"
   # - "serverfqdn"

  
 
epid:
  # WARNING: do not set testmode to true in production environments
  # if testmode is true, EPID signature verification will only
  # fail for non-signature issues (i.e. malformed requests)
  testMode: false
  # TBD: the url below is the used for production purposes
  # url: http://verify.epid-sbx.trustedservices.intel.com
  # the url below is used for testing purposes only
  url: http://verify.epid-sbx.trustedservices.intel.com

#cbor Web Token (cwt) used for to0 and to1 sessions
cwt:
   keystore: 
     path: ctw.p12
     store-type: PKCS12
     password: $(encrypt_password)

workers:
  - org.fidoalliance.fdo.protocol.StandardLogProvider
  - org.fidoalliance.fdo.protocol.StandardMessageDispatcher
  - org.fidoalliance.fdo.protocol.StandardCryptoService
  - org.fidoalliance.fdo.protocol.StandardHttpServer
  - org.fidoalliance.fdo.protocol.StandardDatabaseServer
  - org.fidoalliance.fdo.protocol.StandardCertSignatureFunction
  - org.fidoalliance.fdo.protocol.StandardManufacturerKeySupplier
  - org.fidoalliance.fdo.protocol.StandardOwnerKeySupplier
  - org.fidoalliance.fdo.protocol.StandardCwtKeySupplier
  #- org.fidoalliance.fdo.protocol.db.ReuseVoucherReplacementFunction
  - org.fidoalliance.fdo.protocol.StandardReplacementKeySupplier
  - org.fidoalliance.fdo.protocol.SelfSignedHttpClientSupplier
  #- org.fidoalliance.fdo.protocol.HttpOwnerSchemeSupplier 
  - org.fidoalliance.fdo.protocol.StandardOwnerSchemeSupplier 
  - org.fidoalliance.fdo.protocol.UntrustedRendezvousAcceptFunction
  #- org.fidoalliance.fdo.protocol.db.TrustedRendezvousAcceptFunction
  - org.fidoalliance.fdo.protocol.db.OnDieCertificateManager
  - org.fidoalliance.fdo.protocol.db.To0Scheduler
  - org.fidoalliance.fdo.protocol.db.StandardSessionCleaner
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreInputStream
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreOutputStream
  - org.fidoalliance.fdo.protocol.db.StandardValidityDaysSupplier
  - org.fidoalliance.fdo.protocol.db.StandardRendezvousInfoSupplier
  - org.fidoalliance.fdo.protocol.db.StandardServerSessionManager
  #- org.fidoalliance.fdo.protocol.db.StandardVoucherStorageFunction
  - org.fidoalliance.fdo.protocol.db.AutoInjectVoucherStorageFunction
  - org.fidoalliance.fdo.protocol.db.StandardAcceptOwnerFunction
  - org.fidoalliance.fdo.protocol.db.StandardExtraInfoSupplier
  - org.fidoalliance.fdo.protocol.db.StandardVoucherQueryFunction
  - org.fidoalliance.fdo.protocol.db.StandardRvBlobQueryFunction
  - org.fidoalliance.fdo.protocol.db.StandardRvBlobStorageFunction
  #- org.fidoalliance.fdo.protocol.db.ReuseVoucherReplacementFunction 
  - org.fidoalliance.fdo.protocol.db.StandardVoucherReplacementFunction
  - org.fidoalliance.fdo.protocol.db.StandardReplacementVoucherStorageFunction 
  - org.fidoalliance.fdo.protocol.db.StandardRendezvousWaitSecondsSupplier
  - org.fidoalliance.fdo.protocol.db.StandardOwnerInfoSizeSupplier
  - org.fidoalliance.fdo.protocol.db.ConformanceOwnerModule
  - org.fidoalliance.fdo.protocol.db.FdoSysOwnerModule




