hibernate-properties:
  connection.driver_class: org.h2.Driver
  hibernate.connection.username: sa
  hibernate.connection.password: ''
  hibernate.connection.url: jdbc:h2:tcp://localhost:9092/./emdb
  hibernate.dialect: org.hibernate.dialect.H2Dialect

system-properties:
  log4j.configurationFile: log4j2.xml
  

http-server:
  http_port: 8080
  https_port: 8443
  http_schemes:
  - http
  #- https
  http_timeout: 20000
  https_keystore:
    path: "./creds/ssl.p12"
    password: "changeit"

manufacturer:
   keystore: 
     path: manufacturer.p12
     store-type: PKCS12
     password: Secret

owner:
   keystore: 
     path: owner.12
     store-type: PKCS12
     password: Secret
   replacement:
     keystore: 
       path: replacement.p12
       store-type: PKCS12
       password: Secret

#cbor Web Token (cwt) used for to0 and to1 sessions
cwt:
   keystore: 
     path: ctw.12
     store-type: PKCS12
     password: Secret

workers:
  - org.fidoalliance.fdo.protocol.OnDieCertSignatureFunction
  - org.fidoalliance.fdo.protocol.StandardLogProvider
  - org.fidoalliance.fdo.protocol.StandardMessageDispatcher
  - org.fidoalliance.fdo.protocol.StandardCryptoService
  - org.fidoalliance.fdo.protocol.StandardHttpServer
  - org.fidoalliance.fdo.protocol.StandardDatabaseServer
  - org.fidoalliance.fdo.protocol.StandardCertSignatureFunction
  - org.fidoalliance.fdo.protocol.StandardManufacturerKeySupplier
  - org.fidoalliance.fdo.protocol.StandardOwnerKeySupplier
  - org.fidoalliance.fdo.protocol.StandardCwtKeySupplier
  - org.fidoalliance.fdo.protocol.StandardReplacementKeySupplier
  - org.fidoalliance.fdo.protocol.db.OnDieCertificateManager
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreInputStream
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreOutputStream
  - org.fidoalliance.fdo.protocol.db.StandardValidityDaysSupplier
  - org.fidoalliance.fdo.protocol.db.StandardRendezvousInfoSupplier
  - org.fidoalliance.fdo.protocol.db.StandardServerSessionManager
  - org.fidoalliance.fdo.protocol.db.AutoInjectVoucherStorageFunction
  - org.fidoalliance.fdo.protocol.db.StandardExtraInfoSupplier
  - org.fidoalliance.fdo.protocol.db.StandardVoucherQueryFunction
  - org.fidoalliance.fdo.protocol.db.StandardRvBlobQueryFunction
  - org.fidoalliance.fdo.protocol.db.StandardRvBlobStorageFunction
  - org.fidoalliance.fdo.protocol.db.StandardVoucherReplacementFunction
  - org.fidoalliance.fdo.protocol.db.StandardRendezvousWaitSecondsSupplier
  - org.fidoalliance.fdo.protocol.db.ConformanceOwnerModule

modules:
  - org.fidoalliance.fdo.protocol.db.StandardVoucherStorageFunction
  - org.fidoalliance.fdo.protocol.db.OnDieCertificateManager










  