# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

version: "3.3"

services:

  pri-fdo-mfg:
    image: pri-fdo-mfg
    container_name: pri-fdo-mfg
    expose:
      - "8039"
      - "8038"
    ports:
      - "8039:8039"
      - "8038:8038"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - _JAVA_OPTIONS
    restart: on-failure:5
    env_file:
      - service.env
    secrets:
      - ca-cert.pem
      - server-cert.pem
      - server-key.pem
      - api-user.pem
      - db_password.txt
    volumes:
      - ./app-data:/home/fdo/app-data 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 500m
    mem_reservation: 200m
    cpu_shares: 1024

secrets:
  ca-cert.pem:
    file: ./secrets/ca-cert.pem
  server-cert.pem:
    file: ./secrets/server-cert.pem
  server-key.pem:
    file: ./secrets/server-key.pem
  api-user.pem:
    file: ./secrets/api-user.pem
  db_password.txt:
    file: ./secrets/db_password.txt
