# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

version: "2.4"

services:

  pri-fdo-mfg:
    image: pri-fdo-mfg
    container_name: pri-fdo-mfg
    expose:
      - "8039"
      - "8038"
    ports:
      - "8039:8039"
      - "8038:8038"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - _JAVA_OPTIONS
    restart: on-failure:5
    env_file:
      - service.env
    volumes:
      - ./app-data:/home/fdo/app-data 
    mem_limit: 500m
    mem_reservation: 200m
    cpu_shares: 1024
    pids_limit: 500
    network_mode: host
